name: "Perform a code test"
description: "Installing dependencies and running tests"

inputs:
   nested-folder:
     description: "Folder name if files are nested"
     required: false
   s3-layer-folder:
     description: "S3 layers folder"
     required: false

runs:
   using: "composite"
   steps:
       - name: Read verion number from json file
         id: version
         uses: notiz-dev/github-action-json-property@release
         with: 
           path: 'src/version.json'
           prop_path: 'version'
       - name: Run schell script
         shell: bash
         run: |
           chmod +x "./package.sh"
           "./package.sh"
         env: 
           VERSION: ${{steps.version.outputs.prop}}

