name: "Perform a code test"
description: "Installing dependencies and running tests"

inputs:
   token:
     description: "Token needed to access files "
     required: true
   included-files:
     description: "Path to json folder with version"
     required: true
   source-directory:
     description: "Name of repository needed to create code packages"
     required: true
   repository-type:
     description: "Repository type used in bash code"
     required: true
   nested-folder:
     description: "Folder name if files are nested"
     required: false

runs:
   using: "composite"
   steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install NPM dependencies and create folder with files used in subsequent steps
        shell: bash
        run: | 
          if [[ ${inputs.repository-type} = "typescript)" ]]; then
            if [[ -n ${inputs.nested-folder} ]]
              then
                 cd ${inputs.nested-folder}
              fi
              npm install
              rsync -arv ${inputs.included-files} ./${inputs.source-directory}
          elif [[ ${inputs.repository-type} = "python)" ]]; then
              if [[ -n ${inputs.nested-folder} ]]
              then
                 cd ${inputs.nested-folder}
              fi
              rsync -arv ${inputs.included-files} ./${inputs.source-directory}
          elif [[ ${inputs.repository-type} = "layer)" ]]; then
              exit 0
          else
              exit 1
          fi
